name: aichatbotinterview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  file_picker: ^10.1.2
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
